repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        args: ["--write", "src/**", "*.js", "*.json"]
        exclude: "^dist/.*$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: "^dist/.*$"

  - repo: .
    rev: 8009448ebb4fb1e133674921404bf6c53cc3a96a
    hooks:
      - id: check-build-assets
        exclude: "^dist/.*$"
