repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        args: ["--write", "."]
        types_or: [css, javascript, json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: "^dist/.*$"
  - repo: local
    hooks:
      - id: check-build-assets
        name: Ensure assets are current
        description: Ensure that `npm run build` was run before commiting.
        language: script
        types_or: [css, javascript, svg, json]
        entry: .pre-commit/check-build-assets.sh
