version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    nodejs: "18"
  commands:
    # Generate the documentation
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html

    # Bundle the current version
    - npm install -g npm@next-9
    - npm install
    - npm run build

    # Create directory to serve the examples
    - mkdir --parents $READTHEDOCS_OUTPUT/html/examples

    # Copy our client into the output
    - cp --verbose dist/readthedocs-addons.js $READTHEDOCS_OUTPUT/html/examples

    # Copy all the example sites (Sphinx and Pelican) into the output
    - cp --recursive --verbose public/* $READTHEDOCS_OUTPUT/html/examples/

    # Copy a JSON file that acts as the response of the API
    - cp --verbose public/_/readthedocs-addons.json $READTHEDOCS_OUTPUT/html/examples

    # Show all the files served by Read the Docs
    - find $READTHEDOCS_OUTPUT/html

    # Inject our Javascript file :)
    - cat docs/.inject-js.sh
    - bash docs/.inject-js.sh
