version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    nodejs: "18"
  commands:
    # Generate the documentation
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
